name: Binder build
on:
  push:
    branches:
      - master

jobs:
  trigger-binder-build:
    runs-on: ubuntu-latest
    steps:
      - uses: s-weigand/trigger-mybinder-build@v1
        with:
          target-repo: heremaps/here-map-widget-for-jupyter
          service-name: gh
          debug: true
